title: Tamachirs.com
description: ประสบการณ์ | ไอที | เกม | ท่องเที่ยวและกิจกรรม
lang: th
author:
  name: Tamachirs.com
  email: khunjibna@tamachirs.com

  
baseurl: ""  # ถ้าโฮสต์ที่ root (ไม่มี subfolder)
future: true


google_fonts: Noto Sans Thai
og_image: /assets/image/web-banner.jpg
author_pubkey: npub1p7w6gyufuy3e6fnugvg9an7fyfes085qct2tp8sarctjwqdaqltsg47tzy

lightning:
  lnurl: "https://walletofsatoshi.com/.well-known/lnurlp/khunjibna"
  default_zap: 21

include:
  - .well-known