title: Tamachirs.com
description: บล็อกทดลองเกี่ยวกับชีวิต การเขียน และเทคโนโลยี
lang: th
author:
  name: Tamachirs.com
  email: khunjibna@tamachirs.com

  
baseurl: ""  # ถ้าโฮสต์ที่ root (ไม่มี subfolder)
future: true


google_fonts: Noto Sans Thai
og_image: /assets/img/share.jpg
author_pubkey: npub1p7w6gyufuy3e6fnugvg9an7fyfes085qct2tp8sarctjwqdaqltsg47tzy

lightning:
  lnurl: "https://walletofsatoshi.com/.well-known/lnurlp/khunjibna"
  default_zap: 100

include:
  - .well-known