title: Tamachirs.com
description: บล็อกทดลองเกี่ยวกับชีวิต การเขียน และเทคโนโลยี
lang: th
author:
  name: Tamachirs.com
  email: khunjibna@tamachirs.com

  
baseurl: ""  # ถ้าโฮสต์ที่ root (ไม่มี subfolder)
future: true
